USE Upysusa

CREATE TABLE SUCURSALES(
    ID_SUCURSAL INT PRIMARY KEY,
    TIPO_OPERACION VARCHAR(120),
    CALLE VARCHAR(120),
    NUMERO INT,
    CP INT,
    COLONIA VARCHAR(120),
    MUNICIPIO VARCHAR(120),
    ESTADO VARCHAR(120),
    NO_EMPLEADOS INT,
);

CREATE TABLE CATALOGO_GASTOS (
	ID_NOMBRE_GASTO INT PRIMARY KEY,
	NOMBRE VARCHAR(120)
);


CREATE TABLE TURNO (
    ID_TURNO INT PRIMARY KEY,
    HORA_INICIO DATETIME,
	HORA_TERMINO DATETIME
);

CREATE TABLE ESTATUS (
    ID_ESTATUS INT PRIMARY KEY,
    ESTATUS INT
);

CREATE TABLE PUESTO (
    ID_PUESTO INT PRIMARY KEY,
    NOMBRE_PUESTO VARCHAR(50),
	SALARIO_MENSUAL FLOAT
);

CREATE TABLE PROVEEDORES (
    ID_PROVEEDOR INT PRIMARY KEY,
	RFC VARCHAR(13),
    RAZON_SOCIAL VARCHAR(100),
    CORREO_CONTACTO VARCHAR(50),
    CATEGORIA VARCHAR(50)
);







--2DO NIVEL
CREATE TABLE GASTOS (
    ID_GASTO INT PRIMARY KEY,
    MONTO FLOAT,
	ID_SUCURSAL INT,
	ID_NOMBRE_GASTO INT,
	DIA INT,
	MES INT,
	ANO INT,
	FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSALES(ID_SUCURSAL),
	FOREIGN KEY (ID_NOMBRE_GASTO) REFERENCES CATALOGO_GASTOS(ID_NOMBRE_GASTO)
);

CREATE TABLE EMPLEADOS (
    CURP VARCHAR(50) PRIMARY KEY,
	ID_SUCURSAL INT,
	ID_TURNO INT,
	ID_ESTATUS INT,
	ID_PUESTO INT,
    NOMBRE VARCHAR(50),
    APELLIDO_PAT VARCHAR(50),
    APELLIDO_MAT VARCHAR(50),
    SEXO VARCHAR(50),
    FECHA_NACIMIENTO DATETIME,
    DIA_INGRESO INT,
	MES_INGRESO INT,
	ANO_INGRESO INT,
    RFC VARCHAR(20),
    NSS VARCHAR(20),
	FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSALES(ID_SUCURSAL),
	FOREIGN KEY (ID_TURNO) REFERENCES TURNO(ID_TURNO),
	FOREIGN KEY (ID_ESTATUS) REFERENCES ESTATUS(ID_ESTATUS),
	FOREIGN KEY (ID_PUESTO) REFERENCES PUESTO(ID_PUESTO)
);

CREATE TABLE PRODUCTOS (
    ID_PRODUCTO INT PRIMARY KEY,
	ID_PROVEEDOR INT,
    NOMBRE VARCHAR(120),
    CODIGO_BARRAS VARCHAR(120),
    PRECIO_LISTA FLOAT,
    DESCUENTOS FLOAT,
    PRECIO_VENTA FLOAT,
    CATEGORIA VARCHAR(120),
	UNIDAD_MEDIDA VARCHAR(120),
	FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDORES(ID_PROVEEDOR)
);

CREATE TABLE COMPRAS(
	ID_COMPRA BIGINT PRIMARY KEY,
	ID_PROVEEDOR INT,
	NO_PRODUCTOS INT,
	ID_SUCURSAL INT,
	FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSALES(ID_SUCURSAL),
	COSTO_TOTAL_PEDIDO FLOAT,
	FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDORES(ID_PROVEEDOR)
);


CREATE TABLE CAJAS (
    ID_CAJA INT PRIMARY KEY,
    ID_SUCURSAL INT,
	FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSALES(ID_SUCURSAL)
);

CREATE TABLE TICKETS (
    ID_TICKET INT PRIMARY KEY,
    ID_CAJA INT,
    CURP VARCHAR(50),
    ID_SUCURSAL INT,
    FECHA DATETIME,
	HORA DATETIME,
    CLIENTE VARCHAR(255),
    NO_PRODUCTOS INT,
    TIPO_PAGO VARCHAR(50),
    TOTAL_COMPRA FLOAT,
	FOREIGN KEY (ID_CAJA) REFERENCES CAJAS(ID_CAJA),
	FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSALES(ID_SUCURSAL),
	FOREIGN KEY (CURP) REFERENCES EMPLEADOS(CURP)
);

CREATE TABLE COMPRA_POR_PRODUCTO(
    ID_COMPRAXPRODUCTO INT PRIMARY KEY,
    ID_COMPRA BIGINT,
    ID_PRODUCTO INT,
    DIA_INGRESO INT,
    MES_INGRESO INT,
    ANO_INGRESO INT,
    DIA_CADUCIDAD INT,
    MES_CADUCIDAD INT,
    ANO_CADUCIDAD INT,
	FOREIGN KEY (ID_COMPRA) REFERENCES COMPRAS(ID_COMPRA),
	FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);

CREATE TABLE ALMACEN_POR_SUCURSAL(
    ID_SUCURSAL_COMPRA INT PRIMARY KEY,
    ID_SUCURSAL INT,
    ID_COMPRA BIGINT,
    CURP_RECIBIO VARCHAR(50),
	TS_INGRESO DATETIME,
	FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSALES(ID_SUCURSAL),
	FOREIGN KEY (ID_COMPRA) REFERENCES COMPRAS(ID_COMPRA),
	FOREIGN KEY (CURP_RECIBIO) REFERENCES EMPLEADOS(CURP)
);

CREATE TABLE TICKETS_DETALLE(
	ID_PRODUCTOXTICKET INT PRIMARY KEY,
	ID_TICKET INT,
	ID_PRODUCTO INT,
	CANTIDAD INT,
	SUBTOTAL_PRODUCTO FLOAT,
	FOREIGN KEY (ID_TICKET) REFERENCES TICKETS(ID_TICKET),
	FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);

